import os
from dotenv import load_dotenv

load_dotenv()

_USE_REAL_LLM = bool(os.getenv("ANTHROPIC_API_KEY"))

if _USE_REAL_LLM:
    from langchain_anthropic import ChatAnthropic

    _llm = ChatAnthropic(model="claude-sonnet-4-6", temperature=0.2, max_tokens=1000)

    def call_llm(prompt: str) -> str:
        response = _llm.invoke(prompt)
        return response.content

else:
    class MockLLM:

        def plan(self, topic: str):
            return [
                f"Find background/context on: {topic}",
                f"Find recent developments or news about: {topic}",
                f"Find internal guidelines or best practices related to: {topic}",
            ]

        def synthesize(self, topic: str, findings: str) -> str:
            return (
                f"Here's a summary on '{topic}':\n\n{findings}\n\n"
                "(Generated by MockLLM — set ANTHROPIC_API_KEY to use Claude "
                "for real synthesis.)"
            )

    _mock = MockLLM()

    def call_llm(prompt: str) -> str:
        raise NotImplementedError("MockLLM does not support raw prompt calls")


def generate_plan(topic: str):
    if _USE_REAL_LLM:
        prompt = (
            f"Break the research topic '{topic}' into 2-4 short, concrete "
            "research sub-questions. Return ONLY a numbered list, no extra text."
        )
        text = call_llm(prompt)
        steps = [
            line.split(".", 1)[-1].strip()
            for line in text.splitlines()
            if line.strip() and any(ch.isdigit() for ch in line[:3])
        ]
        return steps or [topic]
    else:
        return _mock.plan(topic)


def synthesize_answer(topic: str, findings: str) -> str:
    if _USE_REAL_LLM:
        prompt = (
            f"Topic: {topic}\n\nResearch findings:\n{findings}\n\n"
            "Write a concise, well-organized answer based only on these findings. "
            "Do not invent facts not present above."
        )
        return call_llm(prompt)
    else:
        return _mock.synthesize(topic, findings)