# Mock LLM
class MockLLM:

    # Create simple research plan based on the topic
    def create_plan(self, topic: str) -> list[str]:
        return [
            f"Find background and key concepts about: {topic}",
            f"Find recent developments and trends about: {topic}",
            f"Find internal guidelines and best practices about: {topic}",
        ]

    # Create final response using the research findings 
    def create_summary(self, topic: str, findings: str) -> str:
        return (
            f"Here's a summary on '{topic}':\n\n"
            f"{findings}\n\n"
            "This summary was generated by MockLLM."
        )


mock_llm = MockLLM()

# Create research plan based on topic
def generate_plan(topic: str) -> list[str]:
    return mock_llm.create_plan(topic)

# Final answer based on research findings
def synthesize_answer(topic: str, findings: str) -> str:
    return mock_llm.create_summary(topic, findings)