import os
from dotenv import load_dotenv

load_dotenv()

USE_REAL_LLM = bool(os.getenv("ANTHROPIC_API_KEY"))

if USE_REAL_LLM:
    from langchain_anthropic import ChatAnthropic

    llm = ChatAnthropic(
        model="claude-sonnet-4-6",
        temperature=0.2,
        max_tokens=1000,
    )


def call_llm(prompt: str) -> str:

    if not USE_REAL_LLM:
        raise RuntimeError("A real LLM is not configured.")

    response = llm.invoke(prompt)
    return response.content


class MockLLM:

    def create_plan(self, topic: str) -> list[str]:
        return [
            f"Find background and key concepts about: {topic}",
            f"Find recent developments and trends about: {topic}",
            f"Find internal guidelines and best practices about: {topic}",
        ]

    def create_summary(self, topic: str, findings: str) -> str:
        return (
            f"Here's a summary on '{topic}':\n\n"
            f"{findings}\n\n"
            "(Generated by MockLLM — set ANTHROPIC_API_KEY "
            "to use Claude for real synthesis.)"
        )


mock_llm = MockLLM()


def generate_plan(topic: str) -> list[str]:

    if USE_REAL_LLM:
        prompt = (
            f"Break the research topic '{topic}' into 2-4 short, "
            "concrete research sub-questions. "
            "Return ONLY a numbered list with no extra text."
        )

        text = call_llm(prompt)

        steps = []

        for line in text.splitlines():
            line = line.strip()

            if not line:
                continue

            if line[0].isdigit():
                step = line.split(".", 1)[-1].strip()
                steps.append(step)

        return steps or [topic]

    return mock_llm.create_plan(topic)


def synthesize_answer(topic: str, findings: str) -> str:

    if USE_REAL_LLM:
        prompt = (
            f"Topic: {topic}\n\n"
            f"Research findings:\n{findings}\n\n"
            "Write a concise and well-organized answer based only "
            "on these findings. Do not invent information."
        )

        return call_llm(prompt)

    return mock_llm.create_summary(topic, findings)